/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingprojekt;


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Albert
 */
public class Panel extends javax.swing.JFrame {
private List<String> slowko_polskie = new ArrayList<String>();
private List<String> slowko_angielskie = new ArrayList<String>();
boolean AP=true;
int index=0;
int poprawnych=0;
int niepoprawnych=0;
    /**
     * Creates new form Panel
     */
public void podziel_spacje(String operacyjna)
{
    char[] pom=operacyjna.toCharArray();
    boolean bylo=false;
    String polskie="";
    String angielskie="";
    for(int i=0;i<pom.length;i++)
    {
        if(bylo==false)
        {
            if(pom[i]==' ')bylo=true;
            else
            {
                polskie+=pom[i];
            }
            
        }
        else
        {
            angielskie+=pom[i];
        }
        
    }
    System.out.println(polskie + " + "+ angielskie);
    slowko_polskie.add(polskie);
    slowko_angielskie.add(angielskie);
}
    public Panel() {
        initComponents();
         
          czas.removeAllItems();
          czas.addItem("Present_Simple");
          czas.addItem("Present_Continous");
          czas.addItem("Present_Perfect");
         // czas.addItem("Present_Perfect_Continous");
          czas.addItem("Past_Simple");
          czas.addItem("Past_Continous");
          czas.addItem("Past_Perfect");
       //   czas.addItem("Past_Perfect_Continous");
          czas.addItem("Future_Simple");
          czas.addItem("Future_Continous");
          czas.addItem("Future_Perfect");
        //  czas.addItem("Future_Perfect_Continous");
          czas.setSelectedItem(null);
          Pole_ja.disable();
          Pole_ty.disable();
          Pole_on.disable();
          Pole_my.disable();
          Pole_wy.disable();
          Pole_oni.disable();
          
          String nazwaPliku = "dane.txt";
           String operacyjna;
           BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(nazwaPliku));
            String slowo = null;
            while ((slowo = (br.readLine())) != null) {
                operacyjna = slowo.trim();
               // slowko_polskie.add(operacyjna);
                podziel_spacje(operacyjna);
                //System.out.println(operacyjna);
            }
        }catch (Exception e) {
            System.err.println("Wystapil blad przy wczytywaniu danych");
            e.printStackTrace();
        }
        
       
    }
    public void zapodaj(String ja,String ty,String on, String my, String wy, String oni)
    {
        Pole_ja.setText(ja);
                Pole_ty.setText(ty);
                Pole_on.setText(on);
                Pole_my.setText(my);
                Pole_wy.setText(wy);
                Pole_oni.setText(oni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        czas = new javax.swing.JComboBox();
        przycisk_odmiana = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pole_ja = new javax.swing.JTextField();
        Pole_ty = new javax.swing.JTextField();
        Pole_on = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Pole_my = new javax.swing.JTextField();
        Pole_wy = new javax.swing.JTextField();
        Pole_oni = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        slowko_przed = new javax.swing.JTextField();
        przycisk_losuj = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        slowko_po = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        uwagi = new javax.swing.JTextArea();
        wybierz_jezyk = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        dodaj_polski = new javax.swing.JTextField();
        dodaj_tlumaczenie = new javax.swing.JTextField();
        przycisk_dodaj = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        przycisk_sprawdz = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        informacja_tlumaczenie = new javax.swing.JLabel();
        ile_poprawnych = new javax.swing.JLabel();
        ile_niepoprawnych = new javax.swing.JLabel();
        info_czy_dodano = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        czas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        przycisk_odmiana.setText("Odmień");
        przycisk_odmiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_odmianaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ja-I");

        jLabel2.setText("Ty-You");

        jLabel3.setText("On-He");

        jLabel4.setText("Ona-She");

        jLabel5.setText("Ono-It");

        Pole_ja.setText("0");

        Pole_ty.setText("0");

        Pole_on.setText("0");

        jLabel6.setText("My-We");

        jLabel7.setText("Wy-You");

        jLabel8.setText("Oni-They");

        Pole_my.setText("0");

        Pole_wy.setText("0");

        Pole_oni.setText("0");

        jLabel9.setText("W tym miejscu mozesz losowac slowka:");

        jLabel10.setText("Słówko:");

        przycisk_losuj.setText("Losuj");
        przycisk_losuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_losujActionPerformed(evt);
            }
        });

        jLabel11.setText("Tlumaczenie:");

        uwagi.setColumns(20);
        uwagi.setRows(5);
        jScrollPane1.setViewportView(uwagi);

        wybierz_jezyk.setText("Angielski->Polski");
        wybierz_jezyk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wybierz_jezykActionPerformed(evt);
            }
        });

        jLabel12.setText("Tlumacz");

        przycisk_dodaj.setText("Dodaj do bazy");
        przycisk_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_dodajActionPerformed(evt);
            }
        });

        jLabel14.setText("Uwagi:");

        przycisk_sprawdz.setText("Sprawdz");
        przycisk_sprawdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_sprawdzActionPerformed(evt);
            }
        });

        jLabel15.setText("Dodajac nowe slowka, Polskie wpisuj na lewo");

        jLabel16.setText("Czasy i struktury:");

        jLabel13.setText("Nie, wpisuj polskich znakow!");

        jLabel17.setText("Informacja o tlumaczeniach:");

        informacja_tlumaczenie.setText("---");

        ile_poprawnych.setText("Poprawnych:");

        ile_niepoprawnych.setText("Niepoprawnych:");

        jLabel18.setText("Spacje zastępuj podłogą!");

        jLabel19.setText("Aby program działał poprawnie:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(czas, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(przycisk_odmiana)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pole_ja, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pole_ty))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pole_on, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pole_my, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Pole_oni, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(Pole_wy, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacja_tlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ile_niepoprawnych, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(ile_poprawnych, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wybierz_jezyk)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(info_czy_dodano, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(slowko_przed, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(przycisk_losuj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(slowko_po, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dodaj_polski, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(dodaj_tlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(przycisk_dodaj)
                                    .addComponent(przycisk_sprawdz)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(czas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(przycisk_odmiana))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Pole_ja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Pole_ty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Pole_on, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(informacja_tlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ile_poprawnych))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ile_niepoprawnych)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Pole_my, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Pole_wy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Pole_oni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wybierz_jezyk))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(slowko_przed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(slowko_po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(przycisk_losuj)
                                    .addComponent(przycisk_sprawdz))))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(info_czy_dodano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(przycisk_dodaj)
                                .addComponent(dodaj_polski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dodaj_tlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przycisk_losujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_losujActionPerformed
     
        Random generator = new Random();
        if(AP==true)
        {
            index=generator.nextInt(slowko_angielskie.size());
            String angielskie=slowko_angielskie.get(index);
            slowko_przed.setText(angielskie);
        }
        else
        {
            index=generator.nextInt(slowko_polskie.size());
        String polskie=slowko_polskie.get(index);
        slowko_przed.setText(polskie);
        }
    }//GEN-LAST:event_przycisk_losujActionPerformed
 
    private void przycisk_odmianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_odmianaActionPerformed
        // TODO add your handling code here:
        String wybrany_czas=(String)czas.getSelectedItem();
        String reszta;
        
            if(wybrany_czas=="Present_Simple")
            {
                uwagi.setText(" Czas teraźniejszy. Używamy do czynności wykonywanych regularnie");
               zapodaj("verb","verb","verb +s","verb","verb","verb");
            }
            if(wybrany_czas=="Present_Continous")
            {
                uwagi.setText(" Czas teraźniejszy. Używamy do czynności wykonywanych w danym momencie lub tymczasowych");
                 reszta="+verb +ing";
                zapodaj("am "+reszta,"are "+reszta,"is "+reszta,"are "+reszta,"are "+reszta,"are "+reszta);
            }
            if(wybrany_czas=="Present_Perfect")
            {
                uwagi.setText(" Czas teraźniejszy. Używamy do opisnia zdarzeń z przeszłości, które trwają do teraz. Słówka kluczowe: since, for, just, already, ever, never");
                reszta="+ 3 rd verb form/+ed";
               zapodaj("have "+reszta,"have"+reszta,"has"+reszta,"have"+reszta,"have"+reszta,"have"+reszta);
            }
            if(wybrany_czas=="Past_Simple")
            {
                uwagi.setText(" Czas przeszły. Używamy do czynności które skończyły się w przeszłości");
                reszta="+ 2 rd verb form";
               zapodaj(reszta,reszta,reszta,reszta,reszta,reszta);
            }
            if(wybrany_czas=="Past_Continous")
            {
                uwagi.setText(" Czas przeszły. Używamy do czynności które przez dłuższy czas trwały w przeszłości");
                 reszta="+verb +ing";
                zapodaj("was "+reszta,"were "+reszta,"was "+reszta,"were "+reszta,"were "+reszta,"were "+reszta);
            }
            if(wybrany_czas=="Past_Perfect")
            {
                                uwagi.setText(" Czas przeszły. Używamy w zdaniu do odniesienia się do czynności wykonanej przed inną czynnością");
                reszta="had + 3 rd verb form/+ed";
               zapodaj(reszta,reszta,reszta,reszta,reszta,reszta);
            }
        if(wybrany_czas=="Future_Simple")
            {
                uwagi.setText(" Czas przyszły. Używamy do opisania ofert, obietnic i przewidywań");
                reszta="will + verb";
               zapodaj(reszta,reszta,reszta,reszta,reszta,reszta);
            }
            if(wybrany_czas=="Future_Continous")
            {
                uwagi.setText(" Czas przyszły. Używamy do czynności które będziesz wykonywał przez dłuższy czas");
                 reszta="will be + verb +ing";
                zapodaj(reszta,reszta,reszta,reszta,reszta,reszta);
            }
            if(wybrany_czas=="Future_Perfect")
            {
                uwagi.setText(" Czas przyszły. Używamy do opisania czynności któa wystąpi w przyszłości i zostanie wykonana przed konkretnym zdarzeniem");
                reszta="will have + 3 rd verb form/+ed";
               zapodaj(reszta,reszta,reszta,reszta,reszta,reszta);
            }
        
        
        
        
    }//GEN-LAST:event_przycisk_odmianaActionPerformed

    private void wybierz_jezykActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wybierz_jezykActionPerformed
        // TODO add your handling code here:
    
        if(wybierz_jezyk.isSelected())
        {
            wybierz_jezyk.setText("Polski->Angielski"); 
            AP=false;
        }
        else
        {
            wybierz_jezyk.setText("Angielski->Polski");
            AP=true;
        }
        
    }//GEN-LAST:event_wybierz_jezykActionPerformed

    private void przycisk_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_dodajActionPerformed
        // TODO add your handling code here:
    //    PrintWriter zapis = new PrintWriter("dane.txt");
        
           PrintWriter zapis = null;
        try {
             zapis = new PrintWriter("dane.txt");
             String polski=dodaj_polski.getText();
        String angielski=dodaj_tlumaczenie.getText();
        slowko_polskie.add(polski);
        slowko_angielskie.add(angielski);
       
        for(int i=0;i<slowko_polskie.size();i++)
        {
            
                    zapis.println(slowko_polskie.get(i)+" "+slowko_angielskie.get(i));
        }
       
        
        
        
        info_czy_dodano.setText("dodano slowko "+polski +" wraz z tlumaczeniem");
        zapis.close();
            }
        catch (Exception e) {
            System.err.println("Wystapil blad przy zapisywaniu danych");
            e.printStackTrace();
        }
 
       
        
        
        
        
        
        
    }//GEN-LAST:event_przycisk_dodajActionPerformed

    private void przycisk_sprawdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_sprawdzActionPerformed
        // TODO add your handling code here:
        if(slowko_przed.getText()!="")
        {
        
        String po=slowko_po.getText();
         if(AP==true)
        {
            if(po == null ? slowko_polskie.get(index) != null : !po.equals(slowko_polskie.get(index)))
            {
               
                informacja_tlumaczenie.setText(po + " to błąd, poprawnie było by "+slowko_polskie.get(index));
                niepoprawnych++;
                ile_niepoprawnych.setText("Niepoprawnych:"+niepoprawnych);
            }
            else
            {
                 informacja_tlumaczenie.setText("twoje tlumaczenie jest poprawne");
                 poprawnych++;
                ile_poprawnych.setText("Poprawnych:"+poprawnych);
            }
            
            
        }
        else
        {
            if(po == null ? slowko_angielskie.get(index) == null : po.equals(slowko_angielskie.get(index)))
            {
                informacja_tlumaczenie.setText("twoje tlumaczenie jest poprawne");
                poprawnych++;
                ile_poprawnych.setText("Poprawnych:"+poprawnych);
            }
            else
            {
                informacja_tlumaczenie.setText(po+ " to błąd, poprawnie było by "+slowko_angielskie.get(index));
                niepoprawnych++;
                ile_niepoprawnych.setText("Niepoprawnych:"+niepoprawnych);
            }
            
        }
      
        }
        if(slowko_przed.getText()=="")
        {
            informacja_tlumaczenie.setText("nie ma czego tlumaczyc!");
        }
        
    }//GEN-LAST:event_przycisk_sprawdzActionPerformed
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pole_ja;
    private javax.swing.JTextField Pole_my;
    private javax.swing.JTextField Pole_on;
    private javax.swing.JTextField Pole_oni;
    private javax.swing.JTextField Pole_ty;
    private javax.swing.JTextField Pole_wy;
    private javax.swing.JComboBox czas;
    private javax.swing.JTextField dodaj_polski;
    private javax.swing.JTextField dodaj_tlumaczenie;
    private javax.swing.JLabel ile_niepoprawnych;
    private javax.swing.JLabel ile_poprawnych;
    private javax.swing.JLabel info_czy_dodano;
    private javax.swing.JLabel informacja_tlumaczenie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton przycisk_dodaj;
    private javax.swing.JButton przycisk_losuj;
    private javax.swing.JButton przycisk_odmiana;
    private javax.swing.JButton przycisk_sprawdz;
    private javax.swing.JTextField slowko_po;
    private javax.swing.JTextField slowko_przed;
    private javax.swing.JTextArea uwagi;
    private javax.swing.JToggleButton wybierz_jezyk;
    // End of variables declaration//GEN-END:variables
}
